In [1]:
pip install numpy

     ---------------------------------------- 14.8/14.8 MB 9.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Вправа 1. Вводиться число n. Вивести масив разміра nхn, в якому по
діагоналі йдуть числа від 1 до n, а інші числа рівні 0

In [5]:
import time
import sys
N = input('Введите целое число: ')
A = []
start = time.time()
for i in range(int(N)):
    A.append([0]*int(N))
    A[i][i] = i+1
stop = time.time()
print(f"Time: {stop - start}")
A

Введите целое число: 5
Time: 0.0


[[1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0],
 [0, 0, 0, 0, 5]]

In [76]:
import numpy as np
import time
import sys
N = input('Введите целое число: ')
start = time.time()
x = np.arange(1,int(N) + 1)
matrix = np.diag(x)
stop = time.time()
print(f"Time: {stop - start}")
matrix

Введите целове число: 5
Time: 0.0


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

Вправа 3. Вводяться 4 числа n, m, r, c. Вивести масив розміру n на m, в
якому в кожному r -му рядку і в кожному c-му стовпчику стоять 0, а інші
елементи дорівнюють 1.

In [6]:
import time
import sys
entered_list = input("Введите 4 числа n, m, r, c, разделенных пробелом: ").split()
print("Введенный список:", entered_list)
num_list = list(map(int, entered_list))
if num_list[1] % 2 == 0:
    chet = num_list[0]-1
else:
    chet = num_list[0]
k = 0
l = 0
A = []
start = time.time()
for i in range(num_list[0]):
    A.append([1]*num_list[1])             
for i in range(num_list[0]):
    for j in range(num_list[1]):
        if j == l:
            A[i][j] = 0
            l = l + num_list[3]
        if j == chet:
            l = 0
        if k == i:
            A[i][j] = 0
    if k == i:
        k = k + num_list[2]
stop = time.time()
print(f"Time: {stop - start}")
A

Введите 4 числа n, m, r, c, разделенных пробелом: 6 7 2 3
Введенный список: ['6', '7', '2', '3']
Time: 0.0


[[0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 1, 1, 0]]

In [266]:
import numpy as np
import time
import sys
entered_list = input("Введите 4 числа n, m, r, c, разделенных пробелом: ").split()
print("Введенный список:", entered_list)
num_list = list(map(int, entered_list))
k = list(range(0, num_list[0], num_list[2]))
l = list(range(0, num_list[1], num_list[3]))
start = time.time()
c = np.ones((num_list[0], num_list[1]))
c[k, :] = 0
c[:,l] = 0
stop = time.time()
print(f"Time: {stop - start}")
c

Введите 4 числа n, m, r, c, разделенных пробелом: 6 7 2 3
Введенный список: ['6', '7', '2', '3']
Time: 0.0


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 1., 1., 0.]])

Вправа 6. З клавіатури вводиться масив. Замінити всі ненульові елементи на -
1.

In [260]:
import time
import sys
entered_list = input("Введите список чисел разделенных пробелом: ").split()
print("Введенный список:", entered_list)
num_list = list(map(int, entered_list))
start = time.time()
for i in range(len(num_list)):
    if num_list[i] != 0:
        num_list[i] = -1
stop = time.time()
print(f"Time: {stop - start}")
num_list

Введите список чисел разделенных пробелом: 3 4 0 9 7 0 6 0 4 0 3
Введенный список: ['3', '4', '0', '9', '7', '0', '6', '0', '4', '0', '3']
Time: 0.0


[-1, -1, 0, -1, -1, 0, -1, 0, -1, 0, -1]

In [261]:
import numpy as np
import time
import sys
start = time.time()
a = np.asarray(input("Введите список чисел разделенных пробелом: ").split())
b = a.astype(int)
b[b != 0] = -1
stop = time.time()
print(f"Time: {stop - start}")
b

Введите список чисел разделенных пробелом: 3 4 0 9 7 0 6 0 4 0 3
Time: 1.1942064762115479


array([-1, -1,  0, -1, -1,  0, -1,  0, -1,  0, -1])

Вправа 7. З клавіатури вводиться масив. Замінити всі нульові елементи на -1.

In [259]:
import time
import sys
entered_list = input("Введите список чисел разделенных пробелом: ").split()
print("Введенный список:", entered_list)
num_list = list(map(int, entered_list))
start = time.time()
for i in range(len(num_list)):
    if num_list[i] == 0:
        num_list[i] = -1
stop = time.time()
print(f"Time: {stop - start}")
num_list

Введите список чисел разделенных пробелом: 3 4 0 6 5 0 3 0 4
Введенный список: ['3', '4', '0', '6', '5', '0', '3', '0', '4']
Time: 0.0


[3, 4, -1, 6, 5, -1, 3, -1, 4]

In [258]:
import numpy as np
import time
import sys
start = time.time()
a = np.asarray(input("Введите список чисел разделенных пробелом: ").split())
b = a.astype(int)
b[b == 0] = -1
stop = time.time()
print(f"Time: {stop - start}")
b

Введите список чисел разделенных пробелом: 3 4 0 6 5 0 3 0 4
Time: 1.9595043659210205


array([ 3,  4, -1,  6,  5, -1,  3, -1,  4])

Вправа 8. З клавіатури вводиться масив. Підрахувати в ньому кількість
нульових та ненульвих елементів.

In [256]:
import time
import sys
entered_list = input("Введите список чисел разделенных пробелом: ").split()
print("Введенный список:", entered_list)
num_list = list(map(int, entered_list))
c = 0
d = 0
start = time.time()
for i in range(len(num_list)):
    if num_list[i] == 0:
        c = c + 1
    else:
        d = d + 1
stop = time.time()
print(f"Time: {stop - start}")
print(f"Нулів: {c}")
print(f"Не нулів: {d}")

Введите список чисел разделенных пробелом: 3 4 0 9 8 2 4 0 8 4 0
Введенный список: ['3', '4', '0', '9', '8', '2', '4', '0', '8', '4', '0']
Time: 0.0
Нулів: 3
Не нулів: 8


In [257]:
import numpy as np
import time
import sys
start = time.time()
a = np.asarray(input("Введите список чисел разделенных пробелом: ").split())
b = a.astype(int)
print(f"Нулів: {np.sum(b==0)}")
print(f"Не нулів: {np.sum(b!=0)}")
stop = time.time()
print(f"Time: {stop - start}")

Введите список чисел разделенных пробелом: 3 4 0 9 8 2 4 0 8 4 0
Нулів: 3
Не нулів: 8
Time: 1.3262813091278076


Вправа 11. Створити масив одиниць розміром n х n та додати до нього
«рамку», сформовану з 0.

In [255]:
import time
import sys
N = input('Введите целое число: ')
G = int(N) + 2
A = []
start = time.time()
for i in range(G):
    A.append([1]*G)
for i in range(G):
    for j in range(G):
        if i == 0 or i == G - 1 or j == 0 or j == G - 1:
            A[i][j] = 0
stop = time.time()
print(f"Time: {stop - start}")
A

Введите целое число: 4
Time: 0.0


[[0, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 0],
 [0, 0, 0, 0, 0, 0]]

In [4]:
import numpy as np
import time
import sys
N = input('Введите целое число: ')
G = int(N) + 2
start = time.time()
a = np.ones((G,G))
a[0,:] = 0
a[:,0] = 0
a[G-1,:] = 0
a[:,G-1] = 0
stop = time.time()
print(f"Time: {stop - start}")
a

Введите целое число: 4
Time: 0.0


array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

Вправа 16. Заповнити вектор значеннями від 0 до n. Всі значення, що більші
за n/4 та менші за 3n/4 замінити нулями

In [265]:
import time
import sys
N = input('Введите целое число: ')
start = time.time()
a = list(range(0, int(N)+1))
for i in range(len(a)):
    if a[i] > int(N)/4 and a[i] < 3*int(N)/4:
        a[i] = 0
stop = time.time()
print(f"Time: {stop - start}")
a

Введите целое число: 10
Time: 0.0


[0, 1, 2, 0, 0, 0, 0, 0, 8, 9, 10]

In [253]:
import numpy as np
import time
import sys
N = input('Введите целое число: ')
start = time.time()
a = np.arange(start=0,stop=int(N)+1)
a[(a > int(N)/4) & (a < 3*int(N)/4)] = 0
stop = time.time()
print(f"Time: {stop - start}")
a

Введите целое число: 10
Time: 0.0


array([ 0,  1,  2,  0,  0,  0,  0,  0,  8,  9, 10])

Вправа 18. Згенерувати вектор з n випадкових чисел в діапазоні від 0 до 99.
Визначити кількість унікальних чисел в послідовності.

In [7]:
import random
import time
import sys
N = input('Введите целое число: ')
A = []
K = 0
start = time.time()
for i in range(int(N)):
    A.append(random.randint(0, 99))
for i in A:
    if A.count(i) == 1:
        K = K + 1
    else:
        pass
stop = time.time()
print(f"Time: {stop - start}")
print(A)
print(K)

Введите целое число: 30
Time: 0.0
[22, 83, 39, 69, 73, 82, 77, 82, 62, 97, 36, 51, 90, 67, 64, 96, 56, 35, 51, 4, 37, 6, 97, 35, 82, 93, 49, 70, 27, 79]
21


In [8]:
import numpy as np
import random
import time
import sys
N = input('Введите целое число: ')
K = 0
start = time.time()
A = np.random.randint(0,99,int(N))
K = len(np.unique(A))
stop = time.time()
print(f"Time: {stop - start}")
print(A)
print(K)

Введите целое число: 30
Time: 0.0009965896606445312
[ 3 60 81 37 54 28  6 24 76 78 19 89 70 40 91 23 23 78 11 72 60 43 47 47
 97 24 59 59  7 96]
24


Вправа 19. Згенерувати вектор із n елементів, що рівномірно розміщені на
інтервалі (0,1) – тобто обидва кінці інтервалу не включені. Значення вивести
до 3 знаків після коми.

In [338]:
import time
import sys
N = input('Введите целое число: ')
shag = 1 / (int(N) + 1)
A = [0] * int(N)
start = time.time()
for i in range(1,int(N)+1):
    A[i-1] = shag * i
    A[i-1] = round(A[i-1],3)
stop = time.time()
print(f"Time: {stop - start}")
print(round(shag, 3))
A

Введите целое число: 10
Time: 0.0
0.091


[0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818, 0.909]

In [330]:
import numpy as np
import time
import sys
N = input('Введите целое число: ')
start = time.time()
A = np.linspace(0,1,int(N)+2)[1:-1]
A = np.round_(A,decimals = 3)
stop = time.time()
print(f"Time: {stop - start}")
print(A)

Введите целое число: 10
Time: 0.0
[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]


2. Розв’язати систему за допомогою формул Крамера і виконати перевірку за
допомогою:
a) матричного множення;
b) оберненої матриці;
c) функції numpy.linalg.solve().
Порівняти всі рішення за допомогою функції numpy.allclose()

a) матричного множення;

In [54]:
import numpy as np
matrix_list = [[1, 2, 3, 4], [2, 1, 2, 3], [3, 2, 1, 2], [4, 3, 2, 1]]
vector_list = [5, 1, 1, -5]
a = np.array(matrix_list)
b = np.array(vector_list)
d = np.linalg.det(a)
adj = np.linalg.det(a) * np.linalg.inv(a)
a_t = adj.transpose()
x = np.dot(a_t, b)
k = 1 / d
x = x * k
np.allclose(np.dot(a, x), b)

True

b) оберненої матриці;

In [55]:
import numpy as np
matrix_list = [[1, 2, 3, 4], [2, 1, 2, 3], [3, 2, 1, 2], [4, 3, 2, 1]]
vector_list = [5, 1, 1, -5]
a = np.array(matrix_list)
b = np.array(vector_list)
inv_a = np.linalg.inv(a)
x = np.dot(inv_a, b)
np.allclose(np.dot(a, x), b)

True

c) функції numpy.linalg.solve().

In [56]:
import numpy as np
matrix_list = [[1, 2, 3, 4], [2, 1, 2, 3], [3, 2, 1, 2], [4, 3, 2, 1]]
vector_list = [5, 1, 1, -5]
a = np.array(matrix_list)
b = np.array(vector_list)
x = np.linalg.solve(a, b)
np.allclose(np.dot(a, x), b)

True

3. Обчислити значення матричного виразу
а) з використанням універсальних функцій бібліотеки NumPy.
Порівняти всі рішення за допомогою функції numpy.allclose()

In [3]:
import numpy as np
import time
import sys
matrix_list_A = [[5, 1, 7], [-10, -2, 1], [0, 1, 2]]
matrix_list_B = [[2, 4, 1], [3, 1, 0], [7, 2, 1]]
start = time.time()
a = np.array(matrix_list_A)
b = np.array(matrix_list_B)
a_2 = np.linalg.matrix_power(a, 2)
total = a_2 + b
total2 = a - b
multiplication = np.dot(total,total2)
result = multiplication*2
stop = time.time()
print(f"Time: {stop - start}")
print(np.allclose(np.dot(a, a), a_2))
print(np.allclose(total, a_2 + b))
print(np.allclose(total2, a - b))
print(np.allclose(np.dot(total,total2), multiplication))
print(np.allclose(multiplication*2, result))

Time: 0.0
True
True
True
True
True
